# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'PopMatch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PopMatch
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'FirebaseFirestoreSwift'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'FirebaseUI/Storage'
	pod 'Firebase/Analytics'
	pod 'TwilioVideo', '~> 4.3'
	pod 'DLRadioButton', '~> 1.4'
	pod 'FBSDKLoginKit'
	pod 'KCCircularTimer'
	pod 'FBSDKCoreKit'
	pod 'FBSDKShareKit'
end
